Repository hlxsites/merative2, pull requests merged in 2023-08, with the labels that each got.

#306 fix(thought-leadership): adjust the function that checks if a card has a specific attribute value
  blocks/blog-home/blog-home.js
Labels: Thought Leadership

#308 feat(content-band-list): add content-intro block & styles
  blocks/columns/columns.css
  blocks/content-intro/content-intro.css
  blocks/content-intro/content-intro.js
  icons/arrow-purple.svg
  styles/styles.css
Labels: Ready to merge

#311 feat(content): add Content block and cleanup
  blocks/content-intro/content-intro.css
  blocks/content/content.css
  blocks/content/content.js
  blocks/library-metadata/library-metadata.css
  blocks/library-metadata/library-metadata.js
  icons/circular-checkmark.svg
  styles/styles.css
Labels: Ready to merge

#307 fix(video): aligned to design & addressed youtube loading issue
  blocks/video/video.css
  blocks/video/video.js
  scripts/csp.json
Labels: Ready to merge

#300 feat(content-band-checkmarks): Content band checkmarks block changes
  blocks/content-band-checkmarks/content-band-checkmarks.css
  blocks/content-band-checkmarks/content-band-checkmarks.js
  styles/styles.css
Labels: Ready to merge

#313 fix(container): Adjust grid to align with design + adjust button hover effects
  blocks/blog-home/blog-home.css
  blocks/columns/columns.css
  blocks/footer/footer.css
  blocks/header/header.css
  blocks/leadspace/leadspace.css
  blocks/related-resources/related-resources.css
  blocks/teaser-list/teaser-list.css
  blocks/video/video.css
  styles/styles.css
Labels: Ready to merge

#310 feat(back-to-top): remove back to top in favor of Drift
  scripts/scripts.js
  styles/styles.css
Labels: Needs Stakeholders sign off, On-Hold

#322 chore(csp): enable LinkedIn Advertising script
  scripts/csp.json
Labels: Chore

#325 chore(csp): enable google doubleclick in img-src
  scripts/csp.json
Labels: Chore

#324 fix(privacy-policy): Error resolved and scrolling padding added
  scripts/scripts.js
  styles/styles.css
Labels: Ready to merge

#318 feat(quick-links): Add POC LinkTree/Bitly template for showing quick links
  blocks/blog-home/blog-home.css
  blocks/header/header.css
  blocks/pdf-viewer/pdf-viewer.css
  blocks/quick-links-buttons/quick-links-buttons.css
  blocks/quick-links-buttons/quick-links-buttons.js
  blocks/quick-links-header/quick-links-header.css
  blocks/quick-links-header/quick-links-header.js
  blocks/quick-links-socials/quick-links-socials.css
  blocks/quick-links-socials/quick-links-socials.js
  scripts/lib-franklin.js
  scripts/scripts.js
  styles/images/patterns/pattern-health-insights.svg
  styles/images/patterns/pattern-micromedex.svg
  styles/styles.css
Labels: Ready to merge
