Repository hlxsites/merative2, pull requests merged in 2023-07, with the labels that each got.

#265 fix(article-detail): add new design changes for publication placement
  blocks/author-bio/author-bio.css
  blocks/author-bio/author-bio.js
  blocks/tags/tags.css
  scripts/scripts.js
  styles/images/AuthorPlaceholder.svg
  styles/styles.css
Labels: Ready to merge

#266 fix(blog-landing):fix design QA bugs to ensure the page aligns with the Design specs
  blocks/blog-home/blog-home.css
  blocks/blog-home/blog-home.js
  scripts/scripts.js
Labels: Needs design QA

#273 feat(thought-leadership): Add "Hero banner" block
  blocks/hero/hero.css
  blocks/hero/hero.js
  styles/styles.css
Labels: Thought Leadership

#262 Fix: create a variation of carousel block, testimonial block
  blocks/carousel/carousel.css
  blocks/carousel/carousel.js
  icons/mega-phone-simple.svg
Labels: Ready to merge

#286 feat(thought-leadership): add sidebar filtering and results
  blocks/blog-home/blog-home.css
  blocks/blog-home/blog-home.js
  blocks/hero/hero.css
  blocks/thought-leadership-home/thought-leadership-home.css
  blocks/thought-leadership-home/thought-leadership-home.js
  scripts/scripts.js
Labels: Thought Leadership, Ready to merge

#290 chore(csp): add Adobe Target Script and Salesloft Script
  scripts/csp.json
Labels: Chore

#293 feat(pdf-viewer): add design enhancement
  blocks/leadspace/leadspace.css
  blocks/pdf-viewer/pdf-viewer.css
  blocks/pdf-viewer/pdf-viewer.js
  styles/styles.css
Labels: On-Hold

#294 fix(thought-leadership): result results for content type filter
  blocks/thought-leadership-home/thought-leadership-home.js
Labels: Thought Leadership

#279 feat(thought-leadership): add URL/query parameter to sidebar filters
  blocks/blog-home/blog-home.js
  blocks/thought-leadership-home/thought-leadership-home.js
Labels: Thought Leadership

#305 feat(thought-leadership): Merge feature branch into Main
  blocks/blog-home/blog-home.css
  blocks/blog-home/blog-home.js
  blocks/hero/hero.css
  blocks/hero/hero.js
  blocks/linkable-cards/linkable-cards.css
  blocks/linkable-cards/linkable-cards.js
  blocks/podcast/podcast.css
  blocks/podcast/podcast.js
  blocks/related-resources/related-resources.js
  blocks/thought-leadership-home/thought-leadership-home.css
  blocks/thought-leadership-home/thought-leadership-home.js
  head.html
  scripts/csp.json
  scripts/delayed.js
  scripts/scripts.js
  styles/styles.css
Labels: Thought Leadership, Needs Stakeholders sign off
