Repository hlxsites/merative2, pull requests merged in 2023-09, with the labels that each got.

#323 feature(case-study-carousel): Case study carousel block.
  blocks/carousel/carousel.css
  blocks/carousel/carousel.js
  icons/carousel-arrow-left-hover.svg
  icons/carousel-arrow-left.svg
  icons/carousel-arrow-right-hover.svg
  icons/carousel-arrow-right.svg
  styles/styles.css
Labels: Ready to merge

#329 feat(sidebar-column): sidebar column width and gap changes
  styles/styles.css
Labels: Ready to merge

#320 feature(stats-bar): Added statsbar block
  blocks/carousel/carousel.css
  blocks/carousel/carousel.js
  blocks/stat/stat.css
  blocks/stat/stat.js
  styles/styles.css
Labels: Ready to merge

#328 feature(content-band-list-spacing-issue): Content band list spacing issue.
  blocks/columns/columns.css
Labels: 🛠️ fix needed

#330 feat(breadcrumb): Add breadcrumb block fragment
  blocks/breadcrumb/breadcrumb.css
  blocks/breadcrumb/breadcrumb.js
  blocks/header/header.js
  icons/caret-right.svg
  scripts/scripts.js
  styles/styles.css
Labels: Content Entry Update, Needs Re-review

#336 chore(csp): allow googlesyndication and doubleclick
  scripts/csp.json
Labels: Chore

#332 feature(author-bio): Dynamically adding author bio
  blocks/author-bio/author-bio.css
  blocks/author-bio/author-bio.js
Labels: Ready to merge, Content Entry Update

#335 feature(global-cta-modal-implementation): Global CTA Video Modal.
  blocks/linkable-cards/linkable-cards.js
  scripts/lib-franklin.js
Labels: Ready to merge

#339 feat(cta): Implement Global CTA Video Modal to link with YT or .mp4
  blocks/linkable-cards/linkable-cards.js
  scripts/lib-franklin.js
  styles/styles.css
Labels: Ready to merge

#340 feat(support-landing): add Short Cards and Content Text Body blocks
  blocks/accordion/accordion.css
  blocks/content-text-body/content-text-body.css
  blocks/content-text-body/content-text-body.js
  blocks/leadspace/leadspace.css
  blocks/linkable-cards/linkable-cards.css
  blocks/quick-links-buttons/quick-links-buttons.css
  blocks/short-cards/short-cards.css
  blocks/short-cards/short-cards.js
  icons/bg-graphic-01.svg
  icons/bg-graphic-02.svg
  icons/bg-graphic-03.svg
  icons/bg-graphic-04.svg
  icons/bg-graphic-05.svg
  icons/bg-graphic-06.svg
  icons/bg-graphic-07.svg
  icons/bg-graphic-08.svg
  icons/bg-graphic-09.svg
  styles/styles.css
Labels: Ready to merge, Content Entry Update

#341 fix(design-qa): Fix spacing issues within Content Intro & minor bugs seen within Microsite
  blocks/carousel/carousel.css
  blocks/carousel/carousel.js
  blocks/content-intro/content-intro.css
  blocks/content/content.css
Labels: Needs design QA, Needs Re-review
