Repository hlxsites/merative2, pull requests merged in 2023-06, with the labels that each got.

#212 chore(doc): update README and add commitlint
  README.md
  commitlint.config.js
  package-lock.json
  package.json
Labels: documentation

#231 chore(pr-template): adjust PR template to align with Merative's dev process
  .github/pull_request_template.md
Labels: Chore

#227 fix(article-body): Adjust article body to align with design specs
  .stylelintrc.json
  blocks/article-quote/article-quote.css
  blocks/blog-left-nav/blog-left-nav.css
  blocks/blog-left-nav/blog-left-nav.js
  blocks/featured-solution/featured-solution.css
  blocks/featured-solution/featured-solution.js
  blocks/fragment/fragment.css
  blocks/video/video.css
  blocks/video/video.js
  package.json
  styles/styles.css
Labels: Needs design QA

#234 chore(csp): Update CSP to allow for Hotjar Script
  head.html
Labels: Chore

#232 chore(gh-action): add a new GH action for auto-merging changes from main to feat branch
  .github/workflows/merge-main-to-feat-thought-leadership.yaml
Labels: Chore

#235 chore(gh-actions-patch): Add patch to new GH action
  .github/workflows/merge-main-to-feat-thought-leadership.yaml
Labels: Chore

#249 feat(podcast): Add podcast iframe block
  blocks/podcast/podcast.css
  blocks/podcast/podcast.js
  head.html
  scripts/delayed.js
Labels: Needs design QA, Thought Leadership

#243 fix(blog-detail): add correct spacing to paragraph
  styles/styles.css
Labels: Needs design QA
