Repository hlxsites/merative2, pull requests merged in 2023-10, with the labels that each got.

#344 feat(microsite): Add Solution Header and Solution Footer blocks used within custom campaign/microsites
  blocks/columns/columns.css
  blocks/cta/cta.css
  blocks/solution-footer/solution-footer.css
  blocks/solution-footer/solution-footer.js
  blocks/solution-header/solution-header.css
  blocks/solution-header/solution-header.js
  scripts/lib-franklin.js
  scripts/scripts.js
  styles/styles.css
Labels: Ready to merge, Content Entry Update

#345 fix(duplicate-entries): removed duplicate entries
  blocks/blog-home/blog-home.js
  scripts/scripts.js
Labels: Needs Re-review

#348 feat(references): Add a new block called References
  blocks/references/references.css
  blocks/references/references.js
Labels: Ready to merge

#346 feat(support): add blocks (Search, Table, Sidebar) to support pages
  blocks/content-text-body/content-text-body.css
  blocks/right-nav/right-nav.css
  blocks/right-nav/right-nav.js
  blocks/search/search.css
  blocks/search/search.js
  blocks/table/table.css
  blocks/table/table.js
  scripts/scripts.js
  styles/styles.css
  tools/importer/import-docs.js
  tools/importer/import-paths.txt
  tools/importer/import-support.js
Labels: Needs Stakeholders sign off

#350 Creation of a solution block.
  blocks/solution-list/solution-list.css
  blocks/solution-list/solution-list.js
Labels: Ready to merge
